# Generated by Django 3.0.5 on 2020-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('profile_file', models.IntegerField()),
                ('profile_index', models.IntegerField()),
                ('speed_file', models.IntegerField()),
                ('speed_index', models.IntegerField()),
                ('bip_file', models.IntegerField()),
                ('bip_index', models.IntegerField()),
                ('odbyroute_file', models.IntegerField()),
                ('odbyroute_index', models.IntegerField()),
                ('trip_file', models.IntegerField()),
                ('trip_index', models.IntegerField()),
                ('paymentfactor_file', models.IntegerField()),
                ('paymentfactor_index', models.IntegerField()),
                ('general_file', models.IntegerField()),
                ('general_index', models.IntegerField()),
            ],
        ),
    ]
