# Generated by Django 3.2 on 2021-04-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consistencychecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistency',
            name='authority_period_version',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
