# Generated by Django 3.2.4 on 2021-09-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consistencychecker', '0003_consistency_authority_period_index_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistency',
            name='stage_file',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consistency',
            name='stage_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
