# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='path',
            field=models.CharField(max_length=200, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='patternFile',
            field=models.CharField(max_length=100, verbose_name='Patr\xf3n de archivo'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\xdaltima actualizaci\xf3n'),
        ),
    ]
