# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0002_auto_20170717_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Or\xedgen de archivo de carga', 'verbose_name_plural': 'Or\xedgenes de archivos de carga'},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='code',
            field=models.CharField(max_length=50, verbose_name='c\xf3digo'),
        ),
    ]
