# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 15:53


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0004_auto_20170718_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefile',
            name='dataSourcePath',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datamanager.DataSourcePath'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcefile',
            name='fileName',
            field=models.CharField(default=None, max_length=200, verbose_name='Nombre de archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcefileexecutionhistory',
            name='executionEnd',
            field=models.DateTimeField(null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='datasourcefileexecutionhistory',
            name='executionStart',
            field=models.DateTimeField(default=None, verbose_name='Inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcefileexecutionhistory',
            name='fileName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datamanager.DataSourceFile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcefileexecutionhistory',
            name='message',
            field=models.TextField(max_length=500, null=True, verbose_name='Mensaje de error'),
        ),
        migrations.AddField(
            model_name='datasourcefileexecutionhistory',
            name='state',
            field=models.CharField(choices=[('running', 'cargando datos a elastic search'), ('ok', 'Finalizaci\xf3n exitosa'), ('error', 'Finalizaci\xf3n con error')], default=None, max_length=30, verbose_name='Raz\xf3n de termino'),
            preserve_default=False,
        ),
    ]
