# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 19:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0006_auto_20170718_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasourcepath',
            old_name='patternFile',
            new_name='filePattern',
        ),
        migrations.AddField(
            model_name='datasourcefile',
            name='discoverAt',
            field=models.DateTimeField(default=None, verbose_name='Primera vez encontrado'),
            preserve_default=False,
        ),
    ]
