# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0007_auto_20170718_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefile',
            name='lines',
            field=models.IntegerField(default=0),
        ),
    ]
