# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0008_datasourcefile_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefile',
            name='dataSourcePath',
            field=models.CharField(max_length=200),
        ),
    ]
