# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0009_auto_20170727_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.UUIDField(verbose_name='Identificador de trabajo')),
                ('type', models.CharField(choices=[('exporter', 'Carga de datos'), ('uploader', 'Descarga de datos')], max_length=10, verbose_name='Tipo')),
                ('executionStart', models.DateTimeField(verbose_name='Inicio')),
                ('executionEnd', models.DateTimeField(null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('running', 'cargando datos a elastic search'), ('finished', 'Finalizaci\xf3n exitosa'), ('failed', 'Finalizaci\xf3n con error'), ('canceled', 'Cancelado por usuario')], max_length=10, verbose_name='Estado')),
                ('inputs', models.TextField(max_length=500, null=True, verbose_name='Par\xe1metros de llamada')),
                ('errorMessage', models.TextField(max_length=500, null=True, verbose_name='Mensaje de error')),
            ],
        ),
        migrations.RemoveField(
            model_name='datasourcefileexecutionhistory',
            name='fileName',
        ),
        migrations.DeleteModel(
            name='DataSourceFileExecutionHistory',
        ),
    ]
