# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 13:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0011_jobexecution_enqueuetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='jobId',
            field=models.UUIDField(null=True, verbose_name='Identificador de trabajo'),
        ),
    ]
