# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0012_auto_20180308_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcepath',
            name='code',
            field=models.CharField(max_length=50, verbose_name='C\xf3digo'),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='status',
            field=models.CharField(choices=[('enqueued', 'Encolado, esperando para ejecutar'), ('running', 'cargando datos a elastic search'), ('finished', 'Finalizaci\xf3n exitosa'), ('failed', 'Finalizaci\xf3n con error'), ('canceled', 'Cancelado por usuario')], max_length=10, verbose_name='Estado'),
        ),
    ]
