# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0015_remove_uploaderjobexecution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaderjobexecution',
            name='inputs',
        ),
    ]
