# Generated by Django 1.11.6 on 2018-03-11 14:06


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0017_auto_20180308_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadfile',
            old_name='discoverAt',
            new_name='discoveredAt',
        ),
        migrations.AddField(
            model_name='loadfile',
            name='lastModified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\xdaltima modificaci\xf3n'),
            preserve_default=False,
        ),
    ]
