# Generated by Django 1.11.6 on 2018-03-12 15:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0018_auto_20180311_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcepath',
            name='code',
        ),
        migrations.AddField(
            model_name='datasourcepath',
            name='indexName',
            field=models.CharField(default='nothing', max_length=50, verbose_name='Nombre del \xedndice'),
            preserve_default=False,
        ),
    ]
