# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0019_auto_20180312_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaderjobexecution',
            name='errorMessage',
            field=models.TextField(default='', max_length=500, verbose_name='Mensaje de error'),
        ),
    ]
