# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0020_auto_20180315_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExporterJobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.UUIDField(null=True, verbose_name='Identificador de trabajo')),
                ('enqueueTimestamp', models.DateTimeField(verbose_name='Encolado')),
                ('executionStart', models.DateTimeField(null=True, verbose_name='Inicio')),
                ('executionEnd', models.DateTimeField(null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('enqueued', 'Encolado, esperando para ejecutar'), ('running', 'cargando datos a elastic search'), ('finished', 'Finalizaci\xf3n exitosa'), ('failed', 'Finalizaci\xf3n con error'), ('canceled', 'Cancelado por usuario')], max_length=10, verbose_name='Estado')),
                ('errorMessage', models.TextField(default='', max_length=500, verbose_name='Mensaje de error')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name': 'Trabajo para exportar datos',
                'verbose_name_plural': 'Trabajos para exportar datos',
            },
        ),
    ]
