# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 18:26


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datamanager', '0021_exporterjobexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporterjobexecution',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
