# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0022_exporterjobexecution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporterjobexecution',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
