# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0025_auto_20180325_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='status',
            field=models.CharField(choices=[('enqueued', 'Encolado'), ('running', 'Cargando datos'), ('finished', 'Finalizaci\xf3n exitosa'), ('failed', 'Finalizaci\xf3n con error'), ('canceled', 'Cancelado por usuario'), ('finished_m', 'Finalizaci\xf3n exitosa pero no se pudo env\xedar correo'), ('expired', 'Vencido')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='uploaderjobexecution',
            name='status',
            field=models.CharField(choices=[('enqueued', 'Encolado'), ('running', 'Cargando datos'), ('finished', 'Finalizaci\xf3n exitosa'), ('failed', 'Finalizaci\xf3n con error'), ('canceled', 'Cancelado por usuario'), ('finished_m', 'Finalizaci\xf3n exitosa pero no se pudo env\xedar correo'), ('expired', 'Vencido')], max_length=10, verbose_name='Estado'),
        ),
    ]
