# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 17:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0028_auto_20180330_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/downloads', location=b'C:\\Users\\cephei\\PycharmProjects\\fondefVizServer\\media\\files'), upload_to='zip/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='fileType',
            field=models.CharField(choices=[('odbyroute', 'Matriz de etapa por servicio'), ('speed', 'Velocidades'), ('trip', 'Viajes'), ('profile', 'Perfil de carga')], max_length=10, verbose_name='Fuente de datos'),
        ),
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='filters',
            field=models.TextField(null=True, verbose_name='Filtros aplicados'),
        ),
    ]
