# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-12 01:16


import datamanager.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0031_auto_20180605_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/downloads', location=b'D:\\PycharmProjects\\fondefVizServer\\media\\files'), upload_to=datamanager.models.get_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='fileType',
            field=models.CharField(choices=[('odbyroute', 'Matriz de etapa por servicio'), ('speed', 'Velocidades'), ('trip', 'Viajes'), ('profile', 'Perfil de carga'), ('busstationdistribution', 'Validaciones en zona paga')], max_length=30, verbose_name='Fuente de datos'),
        ),
    ]
