# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-27 19:08
from __future__ import unicode_literals

import datamanager.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0032_auto_20190811_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/downloads', location="'/home/bastian/PycharmProjects/data"), upload_to=datamanager.models.get_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='fileType',
            field=models.CharField(choices=[('odbyroute', 'Matriz de etapa por servicio'), ('speed', 'Velocidades'), ('trip', 'Viajes'), ('profile', 'Perfil de carga'), ('paymentfactor', 'Validaciones en zona paga'), ('bip', 'Validaciones bip')], max_length=30, verbose_name='Fuente de datos'),
        ),
    ]
