# Generated by Django 3.0.4 on 2020-03-18 18:24

import datamanager.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0033_auto_20200127_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/downloads', location='/home/bastianleaf/Documents/Trabajo/descargas'), upload_to=datamanager.models.get_upload_path, verbose_name='Archivo'),
        ),
    ]
