# Generated by Django 3.2.4 on 2021-07-27 14:39

import datamanager.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0033_auto_20200127_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='fileType',
            field=models.CharField(choices=[('odbyroute', 'Matriz de etapa por servicio'), ('speed', 'Velocidades'), ('trip', 'Viajes'), ('profile', 'Perfil de carga'), ('paymentfactor', 'Validaciones en zona paga'), ('bip', 'Validaciones bip'), ('stage', 'Etapas')], max_length=30, verbose_name='Fuente de datos'),
        ),
    ]
