# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-04 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0032_auto_20200304_1038'),
        ('datamanager', '0033_auto_20200127_1608'),
    ]

    operations = [
    ]
