# Generated by Django 3.0.5 on 2020-06-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0034_auto_20200329_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporterjobexecution',
            name='fileType',
            field=models.CharField(choices=[('odbyroute', 'Matriz de etapa por servicio'), ('speed', 'Velocidades'), ('trip', 'Viajes'), ('profile', 'Perfil de carga'), ('paymentfactor', 'Validaciones en zona paga'), ('bip', 'Validaciones bip'), ('opdata', 'Programas de Operación')], max_length=30, verbose_name='Fuente de datos'),
        ),
    ]
