# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-05 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractions',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActions',
        ),
    ]
