version: '3.7'

services:

  cache:
    image: redis:latest
    networks:
      - cache_network

  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_fondefdev_data:/var/lib/postgresql/data/
    env_file:
      - ./docker_db_env
    networks:
      - database_network

  test:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      command: test
      env_file:
        - ./docker_env
      depends_on:
        - cache
        - db
      networks:
        - database_network
        - cache_network

networks:
  database_network:
    driver: bridge
  cache_network:
    driver: bridge

volumes:
  postgres_fondefdev_data:
  data: