# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeperiod',
            old_name='typeDay',
            new_name='dayType',
        ),
    ]
