# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0002_auto_20170504_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='esId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
