# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0003_timeperiod_esid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esId', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('prettyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HalfHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esId', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('shortName', models.CharField(max_length=10)),
            ],
        ),
    ]
