# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 20:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0004_commune_halfhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfhour',
            name='longName',
            field=models.CharField(default="", max_length=11),
            preserve_default=False,
        ),
    ]
