# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0007_auto_20170907_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esCode', models.IntegerField()),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
