# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0008_operators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operators',
            old_name='esCode',
            new_name='esId',
        ),
    ]
