# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 19:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0009_auto_20171213_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operators',
            new_name='Operator',
        ),
    ]
