# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 20:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0010_auto_20171213_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='esId',
            field=models.IntegerField(verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Nombre'),
        ),
    ]
