# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0012_auto_20171213_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='esId',
            field=models.IntegerField(unique=True, verbose_name='Identificador'),
        ),
    ]
