# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0013_auto_20171213_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halfhour',
            options={'verbose_name': 'Per\xedodo de media hora', 'verbose_name_plural': 'Per\xedodos de media hora'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AddField(
            model_name='halfhour',
            name='authorityPeriodName',
            field=models.CharField(default='', max_length=50, verbose_name='Per\xedodo TranSantiago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halfhour',
            name='esId',
            field=models.IntegerField(verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='halfhour',
            name='longName',
            field=models.CharField(max_length=20, verbose_name='Nombre largo'),
        ),
        migrations.AlterField(
            model_name='halfhour',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='halfhour',
            name='shortName',
            field=models.CharField(max_length=10, verbose_name='Nombre corto'),
        ),
    ]
