# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 16:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0014_auto_20171214_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhour',
            name='authorityPeriodName',
            field=models.CharField(max_length=50, verbose_name='Per\xedodo Transantiago'),
        ),
    ]
