# Generated by Django 1.11.6 on 2018-02-16 14:18


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0016_tipodia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDia',
            new_name='DayType',
        ),
    ]
