# Generated by Django 1.11.6 on 2018-02-25 02:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0019_auto_20180224_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'default_permissions': (), 'verbose_name': 'global_permission'},
        ),
    ]
