# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0020_auto_20180224_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='description',
        ),
    ]
