# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0022_transportmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esId', models.IntegerField(unique=True, verbose_name='Identificador')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Informaci\xf3n de calendario',
                'verbose_name_plural': 'Informaci\xf3n de calendario',
            },
        ),
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esId', models.IntegerField(unique=True, verbose_name='Identificador')),
                ('color', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Descripci\xf3n de d\xeda',
                'verbose_name_plural': 'Descripci\xf3n de d\xedas',
            },
        ),
        migrations.AddField(
            model_name='calendarinfo',
            name='day_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localinfo.DayDescription'),
        ),
    ]
