# Generated by Django 1.11.23 on 2020-01-23 12:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0022_transportmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esId', models.IntegerField(unique=True, verbose_name='Identificador')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Informaci\xf3n de calendario',
                'verbose_name_plural': 'Informaci\xf3n de calendario',
            },
        ),
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=250, verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'descripci\xf3n de d\xeda',
                'verbose_name_plural': 'descripci\xf3nes de d\xedas',
            },
        ),
        migrations.AddField(
            model_name='calendarinfo',
            name='day_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localinfo.DayDescription', verbose_name='Descripci\xf3n de d\xeda'),
        ),
        migrations.RemoveField(
            model_name='calendarinfo',
            name='esId',
        ),
        migrations.AlterField(
            model_name='calendarinfo',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterModelOptions(
            name='calendarinfo',
            options={'verbose_name': 'informaci\xf3n de calendario', 'verbose_name_plural': 'informaci\xf3n de calendario'},
        ),
    ]
