# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0023_auto_20200121_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarinfo',
            name='esId',
        ),
        migrations.RemoveField(
            model_name='daydescription',
            name='esId',
        ),
    ]
