# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0023_auto_20200121_1022_squashed_0029_auto_20200121_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_route_code', models.CharField(max_length=20, unique=True, verbose_name='C\xf3digo transantiago')),
                ('custom_route_code', models.CharField(max_length=30, verbose_name='C\xf3digo custom')),
            ],
            options={
                'verbose_name': 'diccionario de servicios',
                'verbose_name_plural': 'diccionario de servicios',
            },
        ),
    ]
