# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0023_auto_20200121_1022_squashed_0029_auto_20200121_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('category', models.CharField(choices=[('general', 'General'), ('administration', 'Administraci\xf3n'), ('storage', 'Almacenamiento'), ('paymentfactor', 'Validaciones'), ('profile', 'Perfil de carga'), ('speed', 'Velocidades'), ('route', 'Rutas'), ('trip', 'Viajes'), ('global', 'Estad\xedsticas Globales')], default='general', max_length=30, verbose_name='Categor\xeda')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
            },
        ),
    ]
