# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0024_auto_20200121_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='color',
            field=models.CharField(max_length=7)
        ),
    ]
