# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 15:16
from __future__ import unicode_literals

from django.db import migrations
import trix.fields


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0024_faqs_squashed_0027_auto_20200204_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=trix.fields.TrixField(verbose_name='Respuesta'),
        ),
    ]
