# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 15:08
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0024_auto_20200121_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydescription',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
