# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 15:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0024_faqs_squashed_0027_auto_20200204_1014_squashed_0029_remove_faq_title'),
        ('localinfo', '0024_customroute_squashed_0025_auto_20200203_1713'),
    ]

    operations = [
    ]
