# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 15:19

from django.contrib.postgres.operations import UnaccentExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0025_merge_20200206_1219'),
    ]

    operations = [
        UnaccentExtension(),
    ]
