# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0025_auto_20200204_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(verbose_name='Respuesta'),
        ),
    ]
