# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 17:59
from __future__ import unicode_literals

import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0025_merge_20200206_1219'),
    ]

    operations = [
        django.contrib.postgres.operations.UnaccentExtension(
        ),
        migrations.RunSQL(
            sql='CREATE TEXT SEARCH CONFIGURATION french_unaccent(COPY=french);',
        ),
        migrations.RunSQL(
            sql='ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;',
        ),
    ]
