# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0025_auto_20200121_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daydescription',
            options={'verbose_name': 'Descripci\xf3n de d\xeda', 'verbose_name_plural': 'Descripci\xf3nes de d\xedas'},
        ),
        migrations.AlterField(
            model_name='calendarinfo',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='calendarinfo',
            name='day_description',
            field=models.ForeignKey(db_column='Descripci\xf3n de d\xeda', on_delete=django.db.models.deletion.CASCADE, to='localinfo.DayDescription'),
        ),
        migrations.AlterField(
            model_name='daydescription',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripci\xf3n'),
        ),
    ]
