# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('localinfo', '0026_unanccent'),
    ]

    operations = [
        migrations.RunSQL("CREATE TEXT SEARCH CONFIGURATION spanish_unaccent(COPY=spanish);"),

    ]
