# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0026_auto_20200204_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQS',
            new_name='FAQ',
        ),
    ]
