# Generated by Django 1.11.23 on 2020-02-06 18:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0026_unanccent'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE TEXT SEARCH CONFIGURATION french_unaccent(COPY=french);',
        ),
        migrations.RunSQL(
            sql='ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;',
        ),
    ]
