# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0027_auto_20200204_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('administration', 'Administraci\xf3n'), ('storage', 'Almacenamiento'), ('paymentfactor', 'Validaciones'), ('profile', 'Perfil de carga'), ('speed', 'Velocidades'), ('route', 'Rutas'), ('trip', 'Viajes'), ('global', 'Estad\xedsticas Globales')], default='general', max_length=30, verbose_name='Categor\xeda'),
        ),
    ]
