# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('localinfo', '0027_auto_20200206_1229'),
    ]

    operations = [
        migrations.RunSQL("ALTER TEXT SEARCH CONFIGURATION french_unaccent"
                          " ALTER MAPPING FOR hword, hword_part, word"
                          " WITH unaccent, french_stem;"
                          )
    ]
