# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0028_faq_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
    ]
