# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-21 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0028_auto_20200121_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarinfo',
            options={'verbose_name': 'informaci\xf3n de calendario', 'verbose_name_plural': 'informaci\xf3n de calendario'},
        ),
        migrations.AlterModelOptions(
            name='daydescription',
            options={'verbose_name': 'descripci\xf3n de d\xeda', 'verbose_name_plural': 'descripci\xf3nes de d\xedas'},
        ),
    ]
