# Generated by Django 3.0.5 on 2020-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0028_auto_20200302_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_route_code', models.CharField(max_length=30, verbose_name='Código transantiago')),
                ('op_route_code', models.CharField(max_length=30, verbose_name='Código de operación')),
            ],
            options={
                'verbose_name': 'diccionario PO ',
                'verbose_name_plural': 'diccionarios PO',
            },
        ),
        migrations.AlterModelOptions(
            name='daydescription',
            options={'verbose_name': 'descripción de día', 'verbose_name_plural': 'descripciones de días'},
        ),
    ]
