# Generated by Django 3.0.5 on 2020-08-04 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('localinfo', '0029_auto_20200618_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriodDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha ')),
            ],
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE,
                                    to='localinfo.TimePeriodDate', verbose_name='Fecha de validez'),
            preserve_default=False,
        ),
    ]
