# Generated by Django 3.0.5 on 2020-08-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0030_auto_20200803_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomRoute',
        ),
    ]
