# Generated by Django 3.0.5 on 2020-08-05 14:56

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models

fixture_name = 'timeperioddates'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture_name, app_label='localinfo')


class Migration(migrations.Migration):
    dependencies = [
        ('localinfo', '0031_delete_customroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriodDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha ')),
            ],
        ),
        migrations.RunPython(load_fixture, migrations.RunPython.noop),
        migrations.AddField(
            model_name='timeperiod',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='localinfo.TimePeriodDate', verbose_name='Fecha de validez'),
            preserve_default=False,
        ),
    ]
