# Generated by Django 3.1 on 2020-09-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0032_auto_20200805_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Fecha de validez')),
            ],
            options={
                'verbose_name': 'programa de operación',
                'verbose_name_plural': 'programas de operación',
            },
        ),
    ]
