# Generated by Django 3.2 on 2021-05-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0034_auto_20201013_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halfhour',
            name='authorityPeriodName',
        ),
    ]
