# Generated by Django 3.2 on 2021-05-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0035_remove_halfhour_authorityperiodname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdictionary',
            name='updated_at',
        ),
    ]
