# Generated by Django 3.2.20 on 2023-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0037_opdictionary_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdictionary',
            name='route_na_label',
            field=models.CharField(max_length=60, null=True, verbose_name='Service NA'),
        ),
    ]
