# Generated by Django 3.2.20 on 2023-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localinfo', '0038_opdictionary_route_na_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdictionary',
            name='route_na_label',
            field=models.CharField(default='', max_length=60, verbose_name='Service NA'),
        ),
    ]
