# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsbackup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
