# Generated by Django 3.0.5 on 2020-06-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsbackup', '0003_downloadlink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
